### ISSUE TITLE
compile LIS failed

### ISSUE THREAD

**Issue by ninglk** [NESII/lishydro#2]
**Describe the bug**

./core/LIS_timeMgrMod.F90(21): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [ESMF]
  use ESMF
------^
../core/LIS_timeMgrMod.F90(78): error #6457: This derived type name has not been declared.   [ESMF_TIME]
  type(ESMF_Time),  save     :: LIS_twStartTime
-------^
../core/LIS_timeMgrMod.F90(79): error #6457: This derived type name has not been declared.   [ESMF_TIME]
  type(ESMF_Time),  save     :: LIS_twStopTime
-------^
../core/LIS_timeMgrMod.F90(80): error #6457: This derived type name has not been declared.   [ESMF_TIME]
  type(ESMF_Time),  save     :: LIS_twMidTime
-------^
../core/LIS_timeMgrMod.F90(113): error #6457: This derived type name has not been declared.   [ESMF_CLOCK]
  type(ESMF_Clock), save     :: LIS_clock
-------^
../core/LIS_timeMgrMod.F90(114): error #6457: This derived type name has not been declared.   [ESMF_CALENDAR]
  type(ESMF_Calendar), save  :: LIS_calendar
-------^
../core/LIS_timeMgrMod.F90(166): error #6457: This derived type name has not been declared.   [ESMF_TIME]
    type(ESMF_Time)         :: startTime, stopTime
---------^
../core/LIS_timeMgrMod.F90(167): error #6457: This derived type name has not been declared.   [ESMF_TIMEINTERVAL]
    type(ESMF_TimeInterval) :: timeStep, tw
---------^
../core/LIS_timeMgrMod.F90(295): error #6457: This derived type name has not been declared.   [ESMF_TIME]
    type(ESMF_Time)         :: tTime,stopTime
---------^
../core/LIS_timeMgrMod.F90(296): error #6457: This derived type name has not been declared.   [ESMF_TIMEINTERVAL]
    type(ESMF_TimeInterval) :: tw
---------^
../core/LIS_timeMgrMod.F90(485): error #6457: This derived type name has not been declared.   [ESMF_TIMEINTERVAL]
    type(ESMF_TimeInterval)      :: timeStep
---------^
../core/LIS_timeMgrMod.F90(486): error #6457: This derived type name has not been declared.   [ESMF_TIME]
    type(ESMF_Time)              :: startTime, stopTime
---------^
../core/LIS_timeMgrMod.F90(610): error #6457: This derived type name has not been declared.   [ESMF_TIME]
    type(ESMF_Time) :: currTime
---------^
../core/LIS_timeMgrMod.F90(717): error #6457: This derived type name has not been declared.   [ESMF_TIME]
    type(ESMF_Time) :: currTime
---------^
../core/LIS_timeMgrMod.F90(836): error #6457: This derived type name has not been declared.   [ESMF_TIMEINTERVAL]
    type(ESMF_TimeInterval) :: timestep
---------^
../core/LIS_timeMgrMod.F90(1526): error #6457: This derived type name has not been declared.   [ESMF_TIME]
   type(ESMF_Time) :: refTime
--------^
../core/LIS_timeMgrMod.F90(1528): error #6457: This derived type name has not been declared.   [ESMF_TIME]
   type(ESMF_Time) :: start_dekad1, end_dekad1, &
--------^
../core/LIS_timeMgrMod.F90(1532): error #6457: This derived type name has not been declared.   [ESMF_TIMEINTERVAL]
   type(ESMF_TimeInterval) :: offset_interval, &
--------^
../core/LIS_timeMgrMod.F90(1701): error #6457: This derived type name has not been declared.   [ESMF_TIME]
   type(ESMF_Time)         :: startTime, endTime
--------^
../core/LIS_timeMgrMod.F90(1702): error #6457: This derived type name has not been declared.   [ESMF_TIMEINTERVAL]
   type(ESMF_TimeInterval) :: seconds
--------^
../core/LIS_timeMgrMod.F90(1915): error #6457: This derived type name has not been declared.   [ESMF_TIME]
    type(ESMF_Time)              :: currTime
---------^
../core/LIS_timeMgrMod.F90(2639): error #6457: This derived type name has not been declared.   [ESMF_TIME]
    type(ESMF_Time)         :: time1
---------^
../core/LIS_timeMgrMod.F90(2640): error #6457: This derived type name has not been declared.   [ESMF_TIMEINTERVAL]
    type(ESMF_TimeInterval) :: timeStep
---------^
../core/LIS_timeMgrMod.F90(3088): error #6457: This derived type name has not been declared.   [ESMF_TIME]
  type(ESMF_Time)              :: currTime
-------^
../core/LIS_timeMgrMod.F90(3089): error #6457: This derived type name has not been declared.   [ESMF_TIMEINTERVAL]
  type(ESMF_TimeInterval)      :: deltaT
-------^
../core/LIS_timeMgrMod.F90(3215): error #6457: This derived type name has not been declared.   [ESMF_TIME]
   type(ESMF_Time)          :: currTime
--------^
../core/LIS_timeMgrMod.F90(3216): error #6457: This derived type name has not been declared.   [ESMF_TIMEINTERVAL]
   type(ESMF_TimeInterval)  :: ts
--------^
../core/LIS_timeMgrMod.F90(69): error #6404: This name does not have a type, and must have an explicit type.   [LIS_TWSTARTTIME]
  PUBLIC :: LIS_twStartTime
------------^
../core/LIS_timeMgrMod.F90(70): error #6404: This name does not have a type, and must have an explicit type.   [LIS_TWSTOPTIME]
  PUBLIC :: LIS_twStopTime
------------^
../core/LIS_timeMgrMod.F90(71): error #6404: This name does not have a type, and must have an explicit type.   [LIS_TWMIDTIME]
  PUBLIC :: LIS_twMidTime
------------^
/tmp/ifort2kSJF5.i90(3535): catastrophic error: Too many errors, exiting
compilation aborted for ../core/LIS_timeMgrMod.F90 (code 1)
make[1]: *** [Makefile:140: LIS_timeMgrMod.o] Error 1

**Comment by danrosen25** [comment]
Hi @ninglk. LIS-Hydro depends on ESMF. if you're building on cheyenne/discover then you can load the ESMFMKFILE using the tcsh build files (i.e. `> source <file_name>`)
[https://github.com/NESII/lishydro/tree/develop/modules](https://github.com/NESII/lishydro/tree/develop/modules)

If you're not building/running on cheyenne/discover then you'll have to follow the LIS user guide to building dependencies. See 'Required Software Libraries'
[https://lis.gsfc.nasa.gov/documentation/lis](https://lis.gsfc.nasa.gov/documentation/lis)
